DROP TABLE IF EXISTS ${table};
DROP TABLE IF EXISTS ${table}_vertices_pgr;
DROP TABLE IF EXISTS __debug_topo_editing;

CREATE TABLE ${table}_vertices_pgr (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    longitude DOUBLE PRECISION,
    latitude DOUBLE PRECISION
);

CREATE TABLE ${table} (
    id varchar,
    osm_id BIGINT,
    source BIGINT REFERENCES ${table}_vertices_pgr(id),
    target BIGINT REFERENCES ${table}_vertices_pgr(id),
    length REAL,
    foot varchar,
    car_forward varchar,
    car_backward varchar,
    bike_forward varchar,
    bike_backward varchar,
    train varchar,
    wkt TEXT
);
